artifact_uri: file:///C:/Users/octav/Documents/Projet 7/API/test_tracking_uri/0/13a36187d85a4bb9863f6fc852e3e494/artifacts
end_time: 1693904127963
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 13a36187d85a4bb9863f6fc852e3e494
run_name: glamorous-elk-191
run_uuid: 13a36187d85a4bb9863f6fc852e3e494
source_name: ''
source_type: 4
source_version: ''
start_time: 1693904127656
status: 3
tags: []
user_id: octav
