artifact_location: file:///C:/Users/octav/Documents/Projet 7/API/test_tracking_uri/0
creation_time: 1693903266461
experiment_id: '0'
last_update_time: 1693903266461
lifecycle_stage: active
name: Default
