artifact_uri: file:///C:/Users/octav/Documents/Projet 7/API/test_tracking_uri/0/3ab633f28f0f40f888c5c555e468758f/artifacts
end_time: 1693903266901
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3ab633f28f0f40f888c5c555e468758f
run_name: skittish-cub-140
run_uuid: 3ab633f28f0f40f888c5c555e468758f
source_name: ''
source_type: 4
source_version: ''
start_time: 1693903266584
status: 3
tags: []
user_id: octav
